'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Contensive.Addons.Reporting.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''select d.id as dropId, d.name as dropName, e.id as emailId, e.name as emailName, d.DateAdded as dropDate
        ''',(select count(*) from ccemaillog where (logtype=1)and(EmailDropID=d.id)) as Sent
        ''',(select count(*) from ccemaillog where (logtype=2)and(EmailDropID=d.id)) as Opened
        ''',(select count(*) from ccemaillog where (logtype=3)and(EmailDropID=d.id)) as Clicked
        ''' from ccemaildrops d 
        ''' left join ccemail e on e.id=d.EmailID
        ''' where (d.dateadded &lt; {dateTo})
        ''' and (d.dateadded &gt; {dateFrom})
        ''' order by d.id desc.
        '''</summary>
        Friend ReadOnly Property sqlReportEmailDrop() As String
            Get
                Return ResourceManager.GetString("sqlReportEmailDrop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select f.name, count(*) as cnt
        '''from cclibrarydownloadlog l 
        '''left join cclibraryfiles f on f.id=l.fileId
        '''where (l.dateadded &lt; {dateTo})
        '''and (l.dateadded &gt; {dateFrom})
        '''group by f.id, f.name
        '''order by cnt desc.
        '''</summary>
        Friend ReadOnly Property sqlReportLibraryFileDownload() As String
            Get
                Return ResourceManager.GetString("sqlReportLibraryFileDownload", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
